"""install_voice.py - make smartvoice's conversation rules resident in Claude Code and Copilot CLI.

Usage:
    python install_voice.py                install for every harness whose home exists
    python install_voice.py --claude       Claude Code only
    python install_voice.py --copilot      Copilot CLI only
    python install_voice.py --uninstall    remove everything this script added
    python install_voice.py --dry-run      print the plan and change nothing

The rules come from the resident block in the resolved voice profile:
references/voice-profiles/<username>.md, else defaultvoice.md, else nothing is
installed (the same resolution smartvoice uses). --profile overrides it with a
profile name or a path.

Claude Code (CLAUDE_CONFIG_DIR, else ~/.claude)
  smartvoice/rules.md, smartvoice/voice_hook.py
      Resident copies, so a moved or offline checkout can't silently drop them.
  output-styles/<style>.md
      The rules as an output style with keep-coding-instructions: true.
  settings.json
      outputStyle, a SubagentStart hook that injects the rules into every
      subagent, and a Stop hook when the profile bans characters.

Copilot CLI (COPILOT_HOME, else ~/.copilot)
  smartvoice/rules.md, smartvoice/voice_hook.py
  copilot-instructions.md
      A marked block holding the rules. Anything else in the file is kept.
  hooks/smartvoice.json
      subagentStart, plus agentStop when the profile bans characters.

Why an output style and not appendSystemPromptFile. Probed on Claude Code
2.1.272 on 2026-09-15: the appendSystemPromptFile settings key loaded nothing,
and only the --append-system-prompt-file launch flag did. A style with
keep-coding-instructions: true kept every default system-prompt section the
probe checked, and Claude Code re-reminds the model of an active style during a
conversation.

Re-running is safe. Every hook this script owns is found by its
smartvoice/voice_hook.py path and replaced, never duplicated. A settings.json,
output style, or copilot-instructions.md this script rewrites in place is
backed up once, beside the original, with a timestamp suffix. That backup also
runs before copilot-instructions.md is deleted on an uninstall that empties
it. Its own resident rules.md and voice_hook.py copies, hooks/smartvoice.json,
and a stale or uninstalled output style are replaced or deleted outright, with
no backup.
"""
import argparse
import getpass
import io
import json
import os
import re
import shutil
import sys
import time
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
PROFILES = SKILL_DIR / "references" / "voice-profiles"
HOOK_SOURCE = Path(__file__).resolve().parent / "voice_hook.py"
OWNED = "smartvoice/voice_hook.py"
VALID_BANS = ("dashes", "semicolons")
BLOCK = re.compile(
    r"<!--\s*smartvoice:resident\s+(?P<attrs>[^>]*?)-->\s*\n(?P<body>.*?)\n\s*<!--\s*/smartvoice:resident\s*-->",
    re.S,
)
ATTR = re.compile(r'(\w+)="([^"]*)"')
GENERATED = "<!-- smartvoice:generated by install_voice.py -->"
BEGIN = "<!-- smartvoice:begin (generated by install_voice.py, edit the voice profile and re-run it) -->"
END = "<!-- smartvoice:end -->"
STAMP = time.strftime("%Y%m%d%H%M%S")


class InstallError(Exception):
    pass


# --- profile ---------------------------------------------------------------

def username():
    return re.split(r"[\\/]", getpass.getuser())[-1].lower()


def resolve_profile(explicit):
    if explicit:
        path = Path(explicit)
        if not path.suffix:
            path = PROFILES / (explicit + ".md")
        if not path.is_file():
            raise InstallError("profile not found: %s" % path)
        return path
    for candidate in (PROFILES / (username() + ".md"), PROFILES / "defaultvoice.md"):
        if candidate.is_file():
            return candidate
    return None


def read_block(profile):
    text = profile.read_text(encoding="utf-8")
    match = BLOCK.search(text)
    if not match:
        raise InstallError("%s has no smartvoice:resident block" % profile.name)
    attrs = dict(ATTR.findall(match.group("attrs")))
    style = attrs.get("style", "").strip()
    if not style or ":" in style:
        raise InstallError("%s: the resident block needs a colon-free style name" % profile.name)
    bans = [b.strip() for b in attrs.get("enforce", "").split(",") if b.strip()]
    unknown = [b for b in bans if b not in VALID_BANS]
    if unknown:
        raise InstallError("%s: unknown enforce value(s): %s" % (profile.name, ", ".join(unknown)))
    body = match.group("body").strip()
    if not body:
        raise InstallError("%s: the resident block is empty" % profile.name)
    return {"style": style, "bans": bans, "body": body, "profile": profile}


# --- file plumbing -----------------------------------------------------------

class Plan:
    def __init__(self, dry_run):
        self.dry_run = dry_run
        self.lines = []
        self.backed_up = set()

    def say(self, harness, text):
        self.lines.append("%s: %s" % (harness, text))

    def backup(self, path):
        if self.dry_run or not path.is_file() or path in self.backed_up:
            return
        shutil.copy2(str(path), str(path) + ".bak-smartvoice-" + STAMP)
        self.backed_up.add(path)

    def write(self, path, text, backup=True):
        if path.is_file() and path.read_text(encoding="utf-8") == text:
            return False
        if self.dry_run:
            return True
        if backup:
            self.backup(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(path.name + ".tmp-smartvoice")
        with io.open(str(tmp), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        os.replace(str(tmp), str(path))
        return True

    def remove(self, path):
        if not path.exists():
            return False
        if not self.dry_run:
            if path.is_dir():
                shutil.rmtree(str(path))
            else:
                path.unlink()
        return True


def load_json(path):
    if not path.is_file():
        return {}
    raw = path.read_text(encoding="utf-8")
    if not raw.strip():
        return {}
    try:
        data = json.loads(raw)
    except ValueError as exc:
        raise InstallError("%s isn't valid JSON (%s), so it was left untouched" % (path, exc))
    if not isinstance(data, dict):
        raise InstallError("%s isn't a JSON object, so it was left untouched" % path)
    return data


def dump_json(data):
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def owned(entry):
    text = " ".join(str(entry.get(k, "")) for k in ("command", "bash", "powershell"))
    return OWNED in text.replace("\\", "/")


# --- commands ----------------------------------------------------------------

def git_bash_available():
    if os.environ.get("CLAUDE_CODE_GIT_BASH_PATH"):
        return True
    found = shutil.which("bash")
    return bool(found) and "git" in found.lower()


def bash_command(python, script, mode, extra):
    posix = lambda p: str(p).replace("\\", "/")
    return " ".join(['"%s"' % posix(python), '"%s"' % posix(script), mode] + extra)


def powershell_command(python, script, mode, extra):
    return " ".join(['& "%s"' % python, '"%s"' % script, mode] + extra)


def mode_args(mode, block, rules_path):
    if mode.endswith("subagent-start"):
        return ["--rules", '"%s"' % str(rules_path).replace("\\", "/")]
    return ["--ban", ",".join(block["bans"])]


# --- Claude Code ---------------------------------------------------------------

def style_filename(style):
    return re.sub(r"[^a-z0-9]+", "-", style.lower()).strip("-") + ".md"


def generated_styles(styles_dir, keep=None):
    if not styles_dir.is_dir():
        return []
    return [
        path for path in sorted(styles_dir.glob("*.md"))
        if path != keep and GENERATED in path.read_text(encoding="utf-8")
    ]


def claude_install(home, block, python, plan):
    resident = home / "smartvoice"
    rules_path = resident / "rules.md"
    script = resident / "voice_hook.py"
    plan.write(rules_path, block["body"] + "\n", backup=False)
    if not plan.dry_run:
        resident.mkdir(parents=True, exist_ok=True)
        shutil.copy2(str(HOOK_SOURCE), str(script))
    plan.say("claude", "resident rules and hook in %s" % resident)

    style_path = home / "output-styles" / style_filename(block["style"])
    for stale in generated_styles(home / "output-styles", keep=style_path):
        plan.remove(stale)
        plan.say("claude", "removed stale output style %s" % stale.name)
    style_text = (
        "---\n"
        "name: %s\n"
        "description: Replies in the %s voice register. Generated by smartvoice, so edit the profile and re-run the installer.\n"
        "keep-coding-instructions: true\n"
        "---\n\n%s\n\n%s\n"
    ) % (block["style"], block["profile"].stem, block["body"], GENERATED)
    if style_path.is_file() and GENERATED not in style_path.read_text(encoding="utf-8"):
        plan.say("claude", "the existing %s gets a timestamped backup before it's replaced" % style_path.name)
    plan.write(style_path, style_text)
    plan.say("claude", "output style %r in %s" % (block["style"], style_path))

    settings_path = home / "settings.json"
    settings = load_json(settings_path)
    hooks = settings.get("hooks") if isinstance(settings.get("hooks"), dict) else {}
    windows = os.name == "nt"
    use_bash = not windows or git_bash_available()
    events = [("SubagentStart", "claude-subagent-start")]
    if block["bans"]:
        events.append(("Stop", "claude-stop"))
    strip_owned_hooks(hooks, ("Stop", "SubagentStart"))
    for event, mode in events:
        extra = mode_args(mode, block, rules_path)
        entry = {"type": "command", "timeout": 15}
        if use_bash:
            entry["command"] = bash_command(python, script, mode, extra)
            if windows:
                entry["shell"] = "bash"
        else:
            entry["command"] = powershell_command(python, script, mode, extra)
            entry["shell"] = "powershell"
        hooks.setdefault(event, []).append({"hooks": [entry]})
    settings["hooks"] = hooks
    settings["outputStyle"] = block["style"]
    plan.write(settings_path, dump_json(settings))
    plan.say("claude", "settings.json: outputStyle, %s hook(s)" % " + ".join(e for e, _ in events))
    if not block["bans"]:
        plan.say("claude", "no Stop hook, since this profile bans no characters")


def strip_owned_hooks(hooks, events):
    for event in events:
        groups = hooks.get(event)
        if not isinstance(groups, list):
            continue
        kept = []
        for group in groups:
            entries = group.get("hooks") if isinstance(group, dict) else None
            if not isinstance(entries, list):
                kept.append(group)
                continue
            remaining = [e for e in entries if not (isinstance(e, dict) and owned(e))]
            if remaining or not entries:
                kept.append(dict(group, hooks=remaining))
        if kept:
            hooks[event] = kept
        else:
            hooks.pop(event, None)


def claude_uninstall(home, plan):
    styles_dir = home / "output-styles"
    removed_styles = []
    for path in generated_styles(styles_dir):
        text = path.read_text(encoding="utf-8")
        name = re.search(r"^name:\s*(.+)$", text, re.M)
        removed_styles.append(name.group(1).strip() if name else "")
        plan.remove(path)
        plan.say("claude", "removed output style %s" % path.name)
    settings_path = home / "settings.json"
    if settings_path.is_file():
        settings = load_json(settings_path)
        changed = False
        hooks = settings.get("hooks")
        if isinstance(hooks, dict):
            before = json.dumps(hooks, sort_keys=True)
            strip_owned_hooks(hooks, list(hooks.keys()))
            if json.dumps(hooks, sort_keys=True) != before:
                changed = True
                if hooks:
                    settings["hooks"] = hooks
                else:
                    settings.pop("hooks", None)
        if settings.get("outputStyle") in removed_styles:
            settings.pop("outputStyle", None)
            changed = True
        if changed and plan.write(settings_path, dump_json(settings)):
            plan.say("claude", "settings.json: removed smartvoice hooks and outputStyle")
    if plan.remove(home / "smartvoice"):
        plan.say("claude", "removed %s" % (home / "smartvoice"))


# --- Copilot CLI -----------------------------------------------------------------

def copilot_install(home, block, python, plan):
    resident = home / "smartvoice"
    rules_path = resident / "rules.md"
    script = resident / "voice_hook.py"
    plan.write(rules_path, block["body"] + "\n", backup=False)
    if not plan.dry_run:
        resident.mkdir(parents=True, exist_ok=True)
        shutil.copy2(str(HOOK_SOURCE), str(script))
    plan.say("copilot", "resident rules and hook in %s" % resident)

    instructions = home / "copilot-instructions.md"
    current = instructions.read_text(encoding="utf-8") if instructions.is_file() else ""
    managed = "%s\n%s\n%s\n" % (BEGIN, block["body"], END)
    plan.write(instructions, replace_block(current, managed))
    plan.say("copilot", "rules block in %s" % instructions)

    hook_events = {}
    events = [("subagentStart", "copilot-subagent-start")]
    if block["bans"]:
        events.append(("agentStop", "copilot-stop"))
    for event, mode in events:
        extra = mode_args(mode, block, rules_path)
        hook_events[event] = [{
            "type": "command",
            "bash": bash_command(python, script, mode, extra),
            "powershell": powershell_command(python, script, mode, extra),
            "timeoutSec": 15,
        }]
    hooks_path = home / "hooks" / "smartvoice.json"
    plan.write(hooks_path, dump_json({"version": 1, "hooks": hook_events}), backup=False)
    plan.say("copilot", "%s: %s" % (hooks_path, " + ".join(e for e, _ in events)))
    if not block["bans"]:
        plan.say("copilot", "no agentStop hook, since this profile bans no characters")


def replace_block(text, managed):
    pattern = re.compile(re.escape(BEGIN.split(" (")[0]) + r".*?" + re.escape(END) + r"\n?", re.S)
    if pattern.search(text):
        return pattern.sub(lambda _m: managed, text, count=1)
    if text and not text.endswith("\n"):
        text += "\n"
    return text + ("\n" if text.strip() else "") + managed


def copilot_uninstall(home, plan):
    instructions = home / "copilot-instructions.md"
    if instructions.is_file():
        text = instructions.read_text(encoding="utf-8")
        cleaned = replace_block(text, "") if BEGIN.split(" (")[0] in text else text
        if cleaned != text:
            if cleaned.strip():
                plan.write(instructions, cleaned.rstrip("\n") + "\n")
            else:
                plan.backup(instructions)
                plan.remove(instructions)
            plan.say("copilot", "removed the rules block from %s" % instructions.name)
    if plan.remove(home / "hooks" / "smartvoice.json"):
        plan.say("copilot", "removed hooks/smartvoice.json")
    if plan.remove(home / "smartvoice"):
        plan.say("copilot", "removed %s" % (home / "smartvoice"))


# --- entry point -----------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Install smartvoice's conversation rules into Claude Code and Copilot CLI.")
    parser.add_argument("--claude", action="store_true", help="target Claude Code")
    parser.add_argument("--copilot", action="store_true", help="target Copilot CLI")
    parser.add_argument("--uninstall", action="store_true", help="remove what this script installed")
    parser.add_argument("--dry-run", action="store_true", help="print the plan and change nothing")
    parser.add_argument("--profile", help="voice profile name or path (default: resolve by username)")
    parser.add_argument("--claude-home", help="default: CLAUDE_CONFIG_DIR, else ~/.claude")
    parser.add_argument("--copilot-home", help="default: COPILOT_HOME, else ~/.copilot")
    parser.add_argument("--python", help="interpreter the hooks run with (default: this one)")
    args = parser.parse_args(argv)

    claude_home = Path(args.claude_home or os.environ.get("CLAUDE_CONFIG_DIR") or Path.home() / ".claude")
    copilot_home = Path(args.copilot_home or os.environ.get("COPILOT_HOME") or Path.home() / ".copilot")
    targets = []
    if args.claude or args.copilot:
        targets = [t for t, wanted in (("claude", args.claude), ("copilot", args.copilot)) if wanted]
    else:
        targets = [t for t, home in (("claude", claude_home), ("copilot", copilot_home)) if home.is_dir()]
    if not targets:
        print("install_voice: found neither %s nor %s. Pass --claude or --copilot." % (claude_home, copilot_home))
        return 1

    plan = Plan(args.dry_run)
    try:
        if args.uninstall:
            if "claude" in targets:
                claude_uninstall(claude_home, plan)
            if "copilot" in targets:
                copilot_uninstall(copilot_home, plan)
        else:
            profile = resolve_profile(args.profile)
            if profile is None:
                print("install_voice: no voice profile resolved, so smartvoice is inactive and nothing was installed.")
                return 0
            block = read_block(profile)
            python = Path(args.python or sys.executable)
            if "claude" in targets:
                claude_install(claude_home, block, python, plan)
            if "copilot" in targets:
                copilot_install(copilot_home, block, python, plan)
    except InstallError as exc:
        print("install_voice: %s" % exc)
        return 1

    prefix = "would change" if args.dry_run else "done"
    for line in plan.lines:
        print("  %s" % line)
    print("install_voice: %s (%s)." % (prefix, ", ".join(targets)))
    if not args.dry_run and not args.uninstall:
        if "claude" in targets:
            print("  Restart Claude Code. It reads output styles and hooks when it starts.")
        print("  Set SMARTVOICE_HOOKS=off for a run that should skip the hooks, like a benchmark arm.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
